-- phpMyAdmin SQL Dump
-- version 4.5.4.1deb2ubuntu2
-- http://www.phpmyadmin.net
--
-- Client :  localhost
-- Généré le :  Lun 26 Février 2018 à 22:22
-- Version du serveur :  5.7.21-0ubuntu0.16.04.1
-- Version de PHP :  7.0.25-0ubuntu0.16.04.1

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données :  `referenciel`
--

-- --------------------------------------------------------

--
-- Structure de la table `refs`
--

CREATE TABLE `refs` (
  `id` int(15) NOT NULL,
  `client` text NOT NULL,
  `context` text NOT NULL,
  `status` varchar(20) NOT NULL DEFAULT 'PUBLISHED',
  `objectifs` text NOT NULL,
  `presentation` text NOT NULL,
  `output` text NOT NULL,
  `preview` text,
  `createdBY` varchar(50) DEFAULT NULL,
  `createdAT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Contenu de la table `refs`
--

INSERT INTO `refs` (`id`, `client`, `context`, `status`, `objectifs`, `presentation`, `output`, `preview`, `createdBY`, `createdAT`) VALUES
(34, 'Medecins du monde', 'Médecins du Monde (ONG) - Association indépendante, Médecins du Monde agit au-delà du soin. Elle dénonce les atteintes à la dignité et aux droits de l\'homme et se bat pour améliorer la situation des populations. Dans le cadre de sa transformation digitale globale, l\'ONG Médecins du Monde désire réaliser la refonte de son site internet. Le projet global était piloté par DDB.', 'PUBLISHED', 'Le projet a consisté à : - Réaliser les spécifications techniques de la plate-forme ; - Assurer les développements techniques HTML du site ; - Assurer l\'intégration du site.', 'L\'objectif est de véhiculer une image « actuelle » : système de navigation moderne accessible depuis un ensemble de terminaux très divers. Il s\'agit de réaliser un accompagnement à la fois technique et méthodologique.', 'Précisions sur le site web : - Site multi langues. - Responsive design : 2 points de rupture seront implémentés sur le site. - Compatible avec IE 9, 10, 11 ; FF, Chrome et Android 4. - Formulaire de contact multi-destinataire. - Inscription à des évènements avec compteur et email de remerciement (création/affichage d\'évènement, formulaire d\'inscription). - Module de cartographie avec affichage de puces sur les différents pays ou régions dans lesquels l\'association intervient. - Mise en place de pages interfacées avec des Webservices de la solution « profilsoft » pour la création d\'un section « offre d\'emploi ».', NULL, 'Moha', '2018-02-24 09:14:21'),
(35, 'Autre client', 'Médecins du Monde (ONG) - Association indépendante, Médecins du Monde agit au-delà du soin. Elle dénonce les atteintes à la dignité et aux droits de l\'homme et se bat pour améliorer la situation des populations. Dans le cadre de sa transformation digitale globale, l\'ONG Médecins du Monde désire réaliser la refonte de son site internet. Le projet global était piloté par DDB.', 'PUBLISHED', 'Le projet a consisté à : - Réaliser les spécifications techniques de la plate-forme ; - Assurer les développements techniques HTML du site ; - Assurer l\'intégration du site.', 'L\'objectif est de véhiculer une image « actuelle » : système de navigation moderne accessible depuis un ensemble de terminaux très divers. Il s\'agit de réaliser un accompagnement à la fois technique et méthodologique.', 'Précisions sur le site web : - Site multi langues. - Responsive design : 2 points de rupture seront implémentés sur le site. - Compatible avec IE 9, 10, 11 ; FF, Chrome et Android 4. - Formulaire de contact multi-destinataire. - Inscription à des évènements avec compteur et email de remerciement (création/affichage d\'évènement, formulaire d\'inscription). - Module de cartographie avec affichage de puces sur les différents pays ou régions dans lesquels l\'association intervient. - Mise en place de pages interfacées avec des Webservices de la solution « profilsoft » pour la création d\'un section « offre d\'emploi ».', NULL, 'Moha', '2018-02-24 09:14:21'),
(36, 'Medecins du monde', 'Médecins du Monde (ONG) - Association indépendante, Médecins du Monde agit au-delà du soin. Elle dénonce les atteintes à la dignité et aux droits de l\'homme et se bat pour améliorer la situation des populations. Dans le cadre de sa transformation digitale globale, l\'ONG Médecins du Monde désire réaliser la refonte de son site internet. Le projet global était piloté par DDB.', 'PUBLISHED', 'Le projet a consisté à : - Réaliser les spécifications techniques de la plate-forme ; - Assurer les développements techniques HTML du site ; - Assurer l\'intégration du site.', 'L\'objectif est de véhiculer une image « actuelle » : système de navigation moderne accessible depuis un ensemble de terminaux très divers. Il s\'agit de réaliser un accompagnement à la fois technique et méthodologique.', 'Précisions sur le site web : - Site multi langues. - Responsive design : 2 points de rupture seront implémentés sur le site. - Compatible avec IE 9, 10, 11 ; FF, Chrome et Android 4. - Formulaire de contact multi-destinataire. - Inscription à des évènements avec compteur et email de remerciement (création/affichage d\'évènement, formulaire d\'inscription). - Module de cartographie avec affichage de puces sur les différents pays ou régions dans lesquels l\'association intervient. - Mise en place de pages interfacées avec des Webservices de la solution « profilsoft » pour la création d\'un section « offre d\'emploi ».', NULL, 'Admin', '2018-02-24 09:14:21'),
(37, 'Autre client', 'Médecins du Monde (ONG) - Association indépendante, Médecins du Monde agit au-delà du soin. Elle dénonce les atteintes à la dignité et aux droits de l\'homme et se bat pour améliorer la situation des populations. Dans le cadre de sa transformation digitale globale, l\'ONG Médecins du Monde désire réaliser la refonte de son site internet. Le projet global était piloté par DDB.', 'PUBLISHED', 'Le projet a consisté à : - Réaliser les spécifications techniques de la plate-forme ; - Assurer les développements techniques HTML du site ; - Assurer l\'intégration du site.', 'L\'objectif est de véhiculer une image « actuelle » : système de navigation moderne accessible depuis un ensemble de terminaux très divers. Il s\'agit de réaliser un accompagnement à la fois technique et méthodologique.', 'Précisions sur le site web : - Site multi langues. - Responsive design : 2 points de rupture seront implémentés sur le site. - Compatible avec IE 9, 10, 11 ; FF, Chrome et Android 4. - Formulaire de contact multi-destinataire. - Inscription à des évènements avec compteur et email de remerciement (création/affichage d\'évènement, formulaire d\'inscription). - Module de cartographie avec affichage de puces sur les différents pays ou régions dans lesquels l\'association intervient. - Mise en place de pages interfacées avec des Webservices de la solution « profilsoft » pour la création d\'un section « offre d\'emploi ».', NULL, 'Admin', '2018-02-24 09:14:21'),
(38, 'Medecins du monde', 'Médecins du Monde (ONG) - Association indépendante, Médecins du Monde agit au-delà du soin. Elle dénonce les atteintes à la dignité et aux droits de l\'homme et se bat pour améliorer la situation des populations. Dans le cadre de sa transformation digitale globale, l\'ONG Médecins du Monde désire réaliser la refonte de son site internet. Le projet global était piloté par DDB.', 'PUBLISHED', 'Le projet a consisté à : - Réaliser les spécifications techniques de la plate-forme ; - Assurer les développements techniques HTML du site ; - Assurer l\'intégration du site.', 'L\'objectif est de véhiculer une image « actuelle » : système de navigation moderne accessible depuis un ensemble de terminaux très divers. Il s\'agit de réaliser un accompagnement à la fois technique et méthodologique.', 'Précisions sur le site web : - Site multi langues. - Responsive design : 2 points de rupture seront implémentés sur le site. - Compatible avec IE 9, 10, 11 ; FF, Chrome et Android 4. - Formulaire de contact multi-destinataire. - Inscription à des évènements avec compteur et email de remerciement (création/affichage d\'évènement, formulaire d\'inscription). - Module de cartographie avec affichage de puces sur les différents pays ou régions dans lesquels l\'association intervient. - Mise en place de pages interfacées avec des Webservices de la solution « profilsoft » pour la création d\'un section « offre d\'emploi ».', NULL, 'Moha', '2018-02-24 09:14:21'),
(39, 'Autre client', 'Médecins du Monde (ONG) - Association indépendante, Médecins du Monde agit au-delà du soin. Elle dénonce les atteintes à la dignité et aux droits de l\'homme et se bat pour améliorer la situation des populations. Dans le cadre de sa transformation digitale globale, l\'ONG Médecins du Monde désire réaliser la refonte de son site internet. Le projet global était piloté par DDB.', 'PUBLISHED', 'Le projet a consisté à : - Réaliser les spécifications techniques de la plate-forme ; - Assurer les développements techniques HTML du site ; - Assurer l\'intégration du site.', 'L\'objectif est de véhiculer une image « actuelle » : système de navigation moderne accessible depuis un ensemble de terminaux très divers. Il s\'agit de réaliser un accompagnement à la fois technique et méthodologique.', 'Précisions sur le site web : - Site multi langues. - Responsive design : 2 points de rupture seront implémentés sur le site. - Compatible avec IE 9, 10, 11 ; FF, Chrome et Android 4. - Formulaire de contact multi-destinataire. - Inscription à des évènements avec compteur et email de remerciement (création/affichage d\'évènement, formulaire d\'inscription). - Module de cartographie avec affichage de puces sur les différents pays ou régions dans lesquels l\'association intervient. - Mise en place de pages interfacées avec des Webservices de la solution « profilsoft » pour la création d\'un section « offre d\'emploi ».', NULL, 'Moha', '2018-02-24 09:14:21'),
(40, 'Medecins du monde', 'Médecins du Monde (ONG) - Association indépendante, Médecins du Monde agit au-delà du soin. Elle dénonce les atteintes à la dignité et aux droits de l\'homme et se bat pour améliorer la situation des populations. Dans le cadre de sa transformation digitale globale, l\'ONG Médecins du Monde désire réaliser la refonte de son site internet. Le projet global était piloté par DDB.', 'PUBLISHED', 'Le projet a consisté à : - Réaliser les spécifications techniques de la plate-forme ; - Assurer les développements techniques HTML du site ; - Assurer l\'intégration du site.', 'L\'objectif est de véhiculer une image « actuelle » : système de navigation moderne accessible depuis un ensemble de terminaux très divers. Il s\'agit de réaliser un accompagnement à la fois technique et méthodologique.', 'Précisions sur le site web : - Site multi langues. - Responsive design : 2 points de rupture seront implémentés sur le site. - Compatible avec IE 9, 10, 11 ; FF, Chrome et Android 4. - Formulaire de contact multi-destinataire. - Inscription à des évènements avec compteur et email de remerciement (création/affichage d\'évènement, formulaire d\'inscription). - Module de cartographie avec affichage de puces sur les différents pays ou régions dans lesquels l\'association intervient. - Mise en place de pages interfacées avec des Webservices de la solution « profilsoft » pour la création d\'un section « offre d\'emploi ».', NULL, 'Admin', '2018-02-24 09:14:21'),
(41, 'Autre client', 'Médecins du Monde (ONG) - Association indépendante, Médecins du Monde agit au-delà du soin. Elle dénonce les atteintes à la dignité et aux droits de l\'homme et se bat pour améliorer la situation des populations. Dans le cadre de sa transformation digitale globale, l\'ONG Médecins du Monde désire réaliser la refonte de son site internet. Le projet global était piloté par DDB.', 'PUBLISHED', 'Le projet a consisté à : - Réaliser les spécifications techniques de la plate-forme ; - Assurer les développements techniques HTML du site ; - Assurer l\'intégration du site.', 'L\'objectif est de véhiculer une image « actuelle » : système de navigation moderne accessible depuis un ensemble de terminaux très divers. Il s\'agit de réaliser un accompagnement à la fois technique et méthodologique.', 'Précisions sur le site web : - Site multi langues. - Responsive design : 2 points de rupture seront implémentés sur le site. - Compatible avec IE 9, 10, 11 ; FF, Chrome et Android 4. - Formulaire de contact multi-destinataire. - Inscription à des évènements avec compteur et email de remerciement (création/affichage d\'évènement, formulaire d\'inscription). - Module de cartographie avec affichage de puces sur les différents pays ou régions dans lesquels l\'association intervient. - Mise en place de pages interfacées avec des Webservices de la solution « profilsoft » pour la création d\'un section « offre d\'emploi ».', NULL, 'Admin', '2018-02-24 09:14:21'),
(42, 'Medecins du monde', 'Médecins du Monde (ONG) - Association indépendante, Médecins du Monde agit au-delà du soin. Elle dénonce les atteintes à la dignité et aux droits de l\'homme et se bat pour améliorer la situation des populations. Dans le cadre de sa transformation digitale globale, l\'ONG Médecins du Monde désire réaliser la refonte de son site internet. Le projet global était piloté par DDB.', 'PUBLISHED', 'Le projet a consisté à : - Réaliser les spécifications techniques de la plate-forme ; - Assurer les développements techniques HTML du site ; - Assurer l\'intégration du site.', 'L\'objectif est de véhiculer une image « actuelle » : système de navigation moderne accessible depuis un ensemble de terminaux très divers. Il s\'agit de réaliser un accompagnement à la fois technique et méthodologique.', 'Précisions sur le site web : - Site multi langues. - Responsive design : 2 points de rupture seront implémentés sur le site. - Compatible avec IE 9, 10, 11 ; FF, Chrome et Android 4. - Formulaire de contact multi-destinataire. - Inscription à des évènements avec compteur et email de remerciement (création/affichage d\'évènement, formulaire d\'inscription). - Module de cartographie avec affichage de puces sur les différents pays ou régions dans lesquels l\'association intervient. - Mise en place de pages interfacées avec des Webservices de la solution « profilsoft » pour la création d\'un section « offre d\'emploi ».', NULL, 'Moha', '2018-02-24 09:14:21'),
(43, 'Autre client', 'Médecins du Monde (ONG) - Association indépendante, Médecins du Monde agit au-delà du soin. Elle dénonce les atteintes à la dignité et aux droits de l\'homme et se bat pour améliorer la situation des populations. Dans le cadre de sa transformation digitale globale, l\'ONG Médecins du Monde désire réaliser la refonte de son site internet. Le projet global était piloté par DDB.', 'PUBLISHED', 'Le projet a consisté à : - Réaliser les spécifications techniques de la plate-forme ; - Assurer les développements techniques HTML du site ; - Assurer l\'intégration du site.', 'L\'objectif est de véhiculer une image « actuelle » : système de navigation moderne accessible depuis un ensemble de terminaux très divers. Il s\'agit de réaliser un accompagnement à la fois technique et méthodologique.', 'Précisions sur le site web : - Site multi langues. - Responsive design : 2 points de rupture seront implémentés sur le site. - Compatible avec IE 9, 10, 11 ; FF, Chrome et Android 4. - Formulaire de contact multi-destinataire. - Inscription à des évènements avec compteur et email de remerciement (création/affichage d\'évènement, formulaire d\'inscription). - Module de cartographie avec affichage de puces sur les différents pays ou régions dans lesquels l\'association intervient. - Mise en place de pages interfacées avec des Webservices de la solution « profilsoft » pour la création d\'un section « offre d\'emploi ».', NULL, 'Moha', '2018-02-24 09:14:21'),
(44, 'Medecins du monde', 'Médecins du Monde (ONG) - Association indépendante, Médecins du Monde agit au-delà du soin. Elle dénonce les atteintes à la dignité et aux droits de l\'homme et se bat pour améliorer la situation des populations. Dans le cadre de sa transformation digitale globale, l\'ONG Médecins du Monde désire réaliser la refonte de son site internet. Le projet global était piloté par DDB.', 'PUBLISHED', 'Le projet a consisté à : - Réaliser les spécifications techniques de la plate-forme ; - Assurer les développements techniques HTML du site ; - Assurer l\'intégration du site.', 'L\'objectif est de véhiculer une image « actuelle » : système de navigation moderne accessible depuis un ensemble de terminaux très divers. Il s\'agit de réaliser un accompagnement à la fois technique et méthodologique.', 'Précisions sur le site web : - Site multi langues. - Responsive design : 2 points de rupture seront implémentés sur le site. - Compatible avec IE 9, 10, 11 ; FF, Chrome et Android 4. - Formulaire de contact multi-destinataire. - Inscription à des évènements avec compteur et email de remerciement (création/affichage d\'évènement, formulaire d\'inscription). - Module de cartographie avec affichage de puces sur les différents pays ou régions dans lesquels l\'association intervient. - Mise en place de pages interfacées avec des Webservices de la solution « profilsoft » pour la création d\'un section « offre d\'emploi ».', NULL, 'Admin', '2018-02-24 09:14:21'),
(45, 'Autre client', 'Médecins du Monde (ONG) - Association indépendante, Médecins du Monde agit au-delà du soin. Elle dénonce les atteintes à la dignité et aux droits de l\'homme et se bat pour améliorer la situation des populations. Dans le cadre de sa transformation digitale globale, l\'ONG Médecins du Monde désire réaliser la refonte de son site internet. Le projet global était piloté par DDB.', 'PUBLISHED', 'Le projet a consisté à : - Réaliser les spécifications techniques de la plate-forme ; - Assurer les développements techniques HTML du site ; - Assurer l\'intégration du site.', 'L\'objectif est de véhiculer une image « actuelle » : système de navigation moderne accessible depuis un ensemble de terminaux très divers. Il s\'agit de réaliser un accompagnement à la fois technique et méthodologique.', 'Précisions sur le site web : - Site multi langues. - Responsive design : 2 points de rupture seront implémentés sur le site. - Compatible avec IE 9, 10, 11 ; FF, Chrome et Android 4. - Formulaire de contact multi-destinataire. - Inscription à des évènements avec compteur et email de remerciement (création/affichage d\'évènement, formulaire d\'inscription). - Module de cartographie avec affichage de puces sur les différents pays ou régions dans lesquels l\'association intervient. - Mise en place de pages interfacées avec des Webservices de la solution « profilsoft » pour la création d\'un section « offre d\'emploi ».', NULL, 'Admin', '2018-02-24 09:14:21'),
(46, 'Medecins du monde', 'Médecins du Monde (ONG) - Association indépendante, Médecins du Monde agit au-delà du soin. Elle dénonce les atteintes à la dignité et aux droits de l\'homme et se bat pour améliorer la situation des populations. Dans le cadre de sa transformation digitale globale, l\'ONG Médecins du Monde désire réaliser la refonte de son site internet. Le projet global était piloté par DDB.', 'PUBLISHED', 'Le projet a consisté à : - Réaliser les spécifications techniques de la plate-forme ; - Assurer les développements techniques HTML du site ; - Assurer l\'intégration du site.', 'L\'objectif est de véhiculer une image « actuelle » : système de navigation moderne accessible depuis un ensemble de terminaux très divers. Il s\'agit de réaliser un accompagnement à la fois technique et méthodologique.', 'Précisions sur le site web : - Site multi langues. - Responsive design : 2 points de rupture seront implémentés sur le site. - Compatible avec IE 9, 10, 11 ; FF, Chrome et Android 4. - Formulaire de contact multi-destinataire. - Inscription à des évènements avec compteur et email de remerciement (création/affichage d\'évènement, formulaire d\'inscription). - Module de cartographie avec affichage de puces sur les différents pays ou régions dans lesquels l\'association intervient. - Mise en place de pages interfacées avec des Webservices de la solution « profilsoft » pour la création d\'un section « offre d\'emploi ».', NULL, 'Moha', '2018-02-24 09:14:21'),
(47, 'Autre client', 'Médecins du Monde (ONG) - Association indépendante, Médecins du Monde agit au-delà du soin. Elle dénonce les atteintes à la dignité et aux droits de l\'homme et se bat pour améliorer la situation des populations. Dans le cadre de sa transformation digitale globale, l\'ONG Médecins du Monde désire réaliser la refonte de son site internet. Le projet global était piloté par DDB.', 'PUBLISHED', 'Le projet a consisté à : - Réaliser les spécifications techniques de la plate-forme ; - Assurer les développements techniques HTML du site ; - Assurer l\'intégration du site.', 'L\'objectif est de véhiculer une image « actuelle » : système de navigation moderne accessible depuis un ensemble de terminaux très divers. Il s\'agit de réaliser un accompagnement à la fois technique et méthodologique.', 'Précisions sur le site web : - Site multi langues. - Responsive design : 2 points de rupture seront implémentés sur le site. - Compatible avec IE 9, 10, 11 ; FF, Chrome et Android 4. - Formulaire de contact multi-destinataire. - Inscription à des évènements avec compteur et email de remerciement (création/affichage d\'évènement, formulaire d\'inscription). - Module de cartographie avec affichage de puces sur les différents pays ou régions dans lesquels l\'association intervient. - Mise en place de pages interfacées avec des Webservices de la solution « profilsoft » pour la création d\'un section « offre d\'emploi ».', NULL, 'Moha', '2018-02-24 09:14:21'),
(48, 'Medecins du monde', 'Médecins du Monde (ONG) - Association indépendante, Médecins du Monde agit au-delà du soin. Elle dénonce les atteintes à la dignité et aux droits de l\'homme et se bat pour améliorer la situation des populations. Dans le cadre de sa transformation digitale globale, l\'ONG Médecins du Monde désire réaliser la refonte de son site internet. Le projet global était piloté par DDB.', 'PUBLISHED', 'Le projet a consisté à : - Réaliser les spécifications techniques de la plate-forme ; - Assurer les développements techniques HTML du site ; - Assurer l\'intégration du site.', 'L\'objectif est de véhiculer une image « actuelle » : système de navigation moderne accessible depuis un ensemble de terminaux très divers. Il s\'agit de réaliser un accompagnement à la fois technique et méthodologique.', 'Précisions sur le site web : - Site multi langues. - Responsive design : 2 points de rupture seront implémentés sur le site. - Compatible avec IE 9, 10, 11 ; FF, Chrome et Android 4. - Formulaire de contact multi-destinataire. - Inscription à des évènements avec compteur et email de remerciement (création/affichage d\'évènement, formulaire d\'inscription). - Module de cartographie avec affichage de puces sur les différents pays ou régions dans lesquels l\'association intervient. - Mise en place de pages interfacées avec des Webservices de la solution « profilsoft » pour la création d\'un section « offre d\'emploi ».', NULL, 'Admin', '2018-02-24 09:14:21'),
(49, 'Autre client', 'Médecins du Monde (ONG) - Association indépendante, Médecins du Monde agit au-delà du soin. Elle dénonce les atteintes à la dignité et aux droits de l\'homme et se bat pour améliorer la situation des populations. Dans le cadre de sa transformation digitale globale, l\'ONG Médecins du Monde désire réaliser la refonte de son site internet. Le projet global était piloté par DDB.', 'PUBLISHED', 'Le projet a consisté à : - Réaliser les spécifications techniques de la plate-forme ; - Assurer les développements techniques HTML du site ; - Assurer l\'intégration du site.', 'L\'objectif est de véhiculer une image « actuelle » : système de navigation moderne accessible depuis un ensemble de terminaux très divers. Il s\'agit de réaliser un accompagnement à la fois technique et méthodologique.', 'Précisions sur le site web : - Site multi langues. - Responsive design : 2 points de rupture seront implémentés sur le site. - Compatible avec IE 9, 10, 11 ; FF, Chrome et Android 4. - Formulaire de contact multi-destinataire. - Inscription à des évènements avec compteur et email de remerciement (création/affichage d\'évènement, formulaire d\'inscription). - Module de cartographie avec affichage de puces sur les différents pays ou régions dans lesquels l\'association intervient. - Mise en place de pages interfacées avec des Webservices de la solution « profilsoft » pour la création d\'un section « offre d\'emploi ».', NULL, 'Admin', '2018-02-24 09:14:21'),
(50, 'Medecins du monde', 'Médecins du Monde (ONG) - Association indépendante, Médecins du Monde agit au-delà du soin. Elle dénonce les atteintes à la dignité et aux droits de l\'homme et se bat pour améliorer la situation des populations. Dans le cadre de sa transformation digitale globale, l\'ONG Médecins du Monde désire réaliser la refonte de son site internet. Le projet global était piloté par DDB.', 'PUBLISHED', 'Le projet a consisté à : - Réaliser les spécifications techniques de la plate-forme ; - Assurer les développements techniques HTML du site ; - Assurer l\'intégration du site.', 'L\'objectif est de véhiculer une image « actuelle » : système de navigation moderne accessible depuis un ensemble de terminaux très divers. Il s\'agit de réaliser un accompagnement à la fois technique et méthodologique.', 'Précisions sur le site web : - Site multi langues. - Responsive design : 2 points de rupture seront implémentés sur le site. - Compatible avec IE 9, 10, 11 ; FF, Chrome et Android 4. - Formulaire de contact multi-destinataire. - Inscription à des évènements avec compteur et email de remerciement (création/affichage d\'évènement, formulaire d\'inscription). - Module de cartographie avec affichage de puces sur les différents pays ou régions dans lesquels l\'association intervient. - Mise en place de pages interfacées avec des Webservices de la solution « profilsoft » pour la création d\'un section « offre d\'emploi ».', NULL, 'Moha', '2018-02-24 09:14:21'),
(51, 'Autre client', 'Médecins du Monde (ONG) - Association indépendante, Médecins du Monde agit au-delà du soin. Elle dénonce les atteintes à la dignité et aux droits de l\'homme et se bat pour améliorer la situation des populations. Dans le cadre de sa transformation digitale globale, l\'ONG Médecins du Monde désire réaliser la refonte de son site internet. Le projet global était piloté par DDB.', 'PUBLISHED', 'Le projet a consisté à : - Réaliser les spécifications techniques de la plate-forme ; - Assurer les développements techniques HTML du site ; - Assurer l\'intégration du site.', 'L\'objectif est de véhiculer une image « actuelle » : système de navigation moderne accessible depuis un ensemble de terminaux très divers. Il s\'agit de réaliser un accompagnement à la fois technique et méthodologique.', 'Précisions sur le site web : - Site multi langues. - Responsive design : 2 points de rupture seront implémentés sur le site. - Compatible avec IE 9, 10, 11 ; FF, Chrome et Android 4. - Formulaire de contact multi-destinataire. - Inscription à des évènements avec compteur et email de remerciement (création/affichage d\'évènement, formulaire d\'inscription). - Module de cartographie avec affichage de puces sur les différents pays ou régions dans lesquels l\'association intervient. - Mise en place de pages interfacées avec des Webservices de la solution « profilsoft » pour la création d\'un section « offre d\'emploi ».', NULL, 'Moha', '2018-02-24 09:14:21'),
(52, 'Medecins du monde', 'Médecins du Monde (ONG) - Association indépendante, Médecins du Monde agit au-delà du soin. Elle dénonce les atteintes à la dignité et aux droits de l\'homme et se bat pour améliorer la situation des populations. Dans le cadre de sa transformation digitale globale, l\'ONG Médecins du Monde désire réaliser la refonte de son site internet. Le projet global était piloté par DDB.', 'PUBLISHED', 'Le projet a consisté à : - Réaliser les spécifications techniques de la plate-forme ; - Assurer les développements techniques HTML du site ; - Assurer l\'intégration du site.', 'L\'objectif est de véhiculer une image « actuelle » : système de navigation moderne accessible depuis un ensemble de terminaux très divers. Il s\'agit de réaliser un accompagnement à la fois technique et méthodologique.', 'Précisions sur le site web : - Site multi langues. - Responsive design : 2 points de rupture seront implémentés sur le site. - Compatible avec IE 9, 10, 11 ; FF, Chrome et Android 4. - Formulaire de contact multi-destinataire. - Inscription à des évènements avec compteur et email de remerciement (création/affichage d\'évènement, formulaire d\'inscription). - Module de cartographie avec affichage de puces sur les différents pays ou régions dans lesquels l\'association intervient. - Mise en place de pages interfacées avec des Webservices de la solution « profilsoft » pour la création d\'un section « offre d\'emploi ».', NULL, 'Admin', '2018-02-24 09:14:21'),
(53, 'Autre client', 'Médecins du Monde (ONG) - Association indépendante, Médecins du Monde agit au-delà du soin. Elle dénonce les atteintes à la dignité et aux droits de l\'homme et se bat pour améliorer la situation des populations. Dans le cadre de sa transformation digitale globale, l\'ONG Médecins du Monde désire réaliser la refonte de son site internet. Le projet global était piloté par DDB.', 'PUBLISHED', 'Le projet a consisté à : - Réaliser les spécifications techniques de la plate-forme ; - Assurer les développements techniques HTML du site ; - Assurer l\'intégration du site.', 'L\'objectif est de véhiculer une image « actuelle » : système de navigation moderne accessible depuis un ensemble de terminaux très divers. Il s\'agit de réaliser un accompagnement à la fois technique et méthodologique.', 'Précisions sur le site web : - Site multi langues. - Responsive design : 2 points de rupture seront implémentés sur le site. - Compatible avec IE 9, 10, 11 ; FF, Chrome et Android 4. - Formulaire de contact multi-destinataire. - Inscription à des évènements avec compteur et email de remerciement (création/affichage d\'évènement, formulaire d\'inscription). - Module de cartographie avec affichage de puces sur les différents pays ou régions dans lesquels l\'association intervient. - Mise en place de pages interfacées avec des Webservices de la solution « profilsoft » pour la création d\'un section « offre d\'emploi ».', NULL, 'Admin', '2018-02-24 09:14:21'),
(54, 'Autre client', 'Médecins du Monde (ONG) - Association indépendante, Médecins du Monde agit au-delà du soin. Elle dénonce les atteintes à la dignité et aux droits de l\'homme et se bat pour améliorer la situation des populations. Dans le cadre de sa transformation digitale globale, l\'ONG Médecins du Monde désire réaliser la refonte de son site internet. Le projet global était piloté par DDB.', 'PUBLISHED', 'Le projet a consisté à : - Réaliser les spécifications techniques de la plate-forme ; - Assurer les développements techniques HTML du site ; - Assurer l\'intégration du site.', 'L\'objectif est de véhiculer une image « actuelle » : système de navigation moderne accessible depuis un ensemble de terminaux très divers. Il s\'agit de réaliser un accompagnement à la fois technique et méthodologique.', 'Précisions sur le site web : - Site multi langues. - Responsive design : 2 points de rupture seront implémentés sur le site. - Compatible avec IE 9, 10, 11 ; FF, Chrome et Android 4. - Formulaire de contact multi-destinataire. - Inscription à des évènements avec compteur et email de remerciement (création/affichage d\'évènement, formulaire d\'inscription). - Module de cartographie avec affichage de puces sur les différents pays ou régions dans lesquels l\'association intervient. - Mise en place de pages interfacées avec des Webservices de la solution « profilsoft » pour la création d\'un section « offre d\'emploi ».', NULL, 'Moha', '2018-02-24 09:14:21'),
(55, 'Medecins du monde', 'Médecins du Monde (ONG) - Association indépendante, Médecins du Monde agit au-delà du soin. Elle dénonce les atteintes à la dignité et aux droits de l\'homme et se bat pour améliorer la situation des populations. Dans le cadre de sa transformation digitale globale, l\'ONG Médecins du Monde désire réaliser la refonte de son site internet. Le projet global était piloté par DDB.', 'PUBLISHED', 'Le projet a consisté à : - Réaliser les spécifications techniques de la plate-forme ; - Assurer les développements techniques HTML du site ; - Assurer l\'intégration du site.', 'L\'objectif est de véhiculer une image « actuelle » : système de navigation moderne accessible depuis un ensemble de terminaux très divers. Il s\'agit de réaliser un accompagnement à la fois technique et méthodologique.', 'Précisions sur le site web : - Site multi langues. - Responsive design : 2 points de rupture seront implémentés sur le site. - Compatible avec IE 9, 10, 11 ; FF, Chrome et Android 4. - Formulaire de contact multi-destinataire. - Inscription à des évènements avec compteur et email de remerciement (création/affichage d\'évènement, formulaire d\'inscription). - Module de cartographie avec affichage de puces sur les différents pays ou régions dans lesquels l\'association intervient. - Mise en place de pages interfacées avec des Webservices de la solution « profilsoft » pour la création d\'un section « offre d\'emploi ».', NULL, 'Admin', '2018-02-24 09:14:21'),
(56, 'Autre client', 'Médecins du Monde (ONG) - Association indépendante, Médecins du Monde agit au-delà du soin. Elle dénonce les atteintes à la dignité et aux droits de l\'homme et se bat pour améliorer la situation des populations. Dans le cadre de sa transformation digitale globale, l\'ONG Médecins du Monde désire réaliser la refonte de son site internet. Le projet global était piloté par DDB.', 'PUBLISHED', 'Le projet a consisté à : - Réaliser les spécifications techniques de la plate-forme ; - Assurer les développements techniques HTML du site ; - Assurer l\'intégration du site.', 'L\'objectif est de véhiculer une image « actuelle » : système de navigation moderne accessible depuis un ensemble de terminaux très divers. Il s\'agit de réaliser un accompagnement à la fois technique et méthodologique.', 'Précisions sur le site web : - Site multi langues. - Responsive design : 2 points de rupture seront implémentés sur le site. - Compatible avec IE 9, 10, 11 ; FF, Chrome et Android 4. - Formulaire de contact multi-destinataire. - Inscription à des évènements avec compteur et email de remerciement (création/affichage d\'évènement, formulaire d\'inscription). - Module de cartographie avec affichage de puces sur les différents pays ou régions dans lesquels l\'association intervient. - Mise en place de pages interfacées avec des Webservices de la solution « profilsoft » pour la création d\'un section « offre d\'emploi ».', NULL, 'Admin', '2018-02-24 09:14:21'),
(57, 'Medecins du monde', 'Médecins du Monde (ONG) - Association indépendante, Médecins du Monde agit au-delà du soin. Elle dénonce les atteintes à la dignité et aux droits de l\'homme et se bat pour améliorer la situation des populations. Dans le cadre de sa transformation digitale globale, l\'ONG Médecins du Monde désire réaliser la refonte de son site internet. Le projet global était piloté par DDB.', 'PUBLISHED', 'Le projet a consisté à : - Réaliser les spécifications techniques de la plate-forme ; - Assurer les développements techniques HTML du site ; - Assurer l\'intégration du site.', 'L\'objectif est de véhiculer une image « actuelle » : système de navigation moderne accessible depuis un ensemble de terminaux très divers. Il s\'agit de réaliser un accompagnement à la fois technique et méthodologique.', 'Précisions sur le site web : - Site multi langues. - Responsive design : 2 points de rupture seront implémentés sur le site. - Compatible avec IE 9, 10, 11 ; FF, Chrome et Android 4. - Formulaire de contact multi-destinataire. - Inscription à des évènements avec compteur et email de remerciement (création/affichage d\'évènement, formulaire d\'inscription). - Module de cartographie avec affichage de puces sur les différents pays ou régions dans lesquels l\'association intervient. - Mise en place de pages interfacées avec des Webservices de la solution « profilsoft » pour la création d\'un section « offre d\'emploi ».', NULL, 'Moha', '2018-02-24 09:14:21'),
(58, 'Autre client', 'Médecins du Monde (ONG) - Association indépendante, Médecins du Monde agit au-delà du soin. Elle dénonce les atteintes à la dignité et aux droits de l\'homme et se bat pour améliorer la situation des populations. Dans le cadre de sa transformation digitale globale, l\'ONG Médecins du Monde désire réaliser la refonte de son site internet. Le projet global était piloté par DDB.', 'PUBLISHED', 'Le projet a consisté à : - Réaliser les spécifications techniques de la plate-forme ; - Assurer les développements techniques HTML du site ; - Assurer l\'intégration du site.', 'L\'objectif est de véhiculer une image « actuelle » : système de navigation moderne accessible depuis un ensemble de terminaux très divers. Il s\'agit de réaliser un accompagnement à la fois technique et méthodologique.', 'Précisions sur le site web : - Site multi langues. - Responsive design : 2 points de rupture seront implémentés sur le site. - Compatible avec IE 9, 10, 11 ; FF, Chrome et Android 4. - Formulaire de contact multi-destinataire. - Inscription à des évènements avec compteur et email de remerciement (création/affichage d\'évènement, formulaire d\'inscription). - Module de cartographie avec affichage de puces sur les différents pays ou régions dans lesquels l\'association intervient. - Mise en place de pages interfacées avec des Webservices de la solution « profilsoft » pour la création d\'un section « offre d\'emploi ».', NULL, 'Moha', '2018-02-24 09:14:21'),
(59, 'Medecins du monde', 'Médecins du Monde (ONG) - Association indépendante, Médecins du Monde agit au-delà du soin. Elle dénonce les atteintes à la dignité et aux droits de l\'homme et se bat pour améliorer la situation des populations. Dans le cadre de sa transformation digitale globale, l\'ONG Médecins du Monde désire réaliser la refonte de son site internet. Le projet global était piloté par DDB.', 'PUBLISHED', 'Le projet a consisté à : - Réaliser les spécifications techniques de la plate-forme ; - Assurer les développements techniques HTML du site ; - Assurer l\'intégration du site.', 'L\'objectif est de véhiculer une image « actuelle » : système de navigation moderne accessible depuis un ensemble de terminaux très divers. Il s\'agit de réaliser un accompagnement à la fois technique et méthodologique.', 'Précisions sur le site web : - Site multi langues. - Responsive design : 2 points de rupture seront implémentés sur le site. - Compatible avec IE 9, 10, 11 ; FF, Chrome et Android 4. - Formulaire de contact multi-destinataire. - Inscription à des évènements avec compteur et email de remerciement (création/affichage d\'évènement, formulaire d\'inscription). - Module de cartographie avec affichage de puces sur les différents pays ou régions dans lesquels l\'association intervient. - Mise en place de pages interfacées avec des Webservices de la solution « profilsoft » pour la création d\'un section « offre d\'emploi ».', NULL, 'Admin', '2018-02-24 09:14:21'),
(60, 'Autre client', 'Médecins du Monde (ONG) - Association indépendante, Médecins du Monde agit au-delà du soin. Elle dénonce les atteintes à la dignité et aux droits de l\'homme et se bat pour améliorer la situation des populations. Dans le cadre de sa transformation digitale globale, l\'ONG Médecins du Monde désire réaliser la refonte de son site internet. Le projet global était piloté par DDB.', 'PUBLISHED', 'Le projet a consisté à : - Réaliser les spécifications techniques de la plate-forme ; - Assurer les développements techniques HTML du site ; - Assurer l\'intégration du site.', 'L\'objectif est de véhiculer une image « actuelle » : système de navigation moderne accessible depuis un ensemble de terminaux très divers. Il s\'agit de réaliser un accompagnement à la fois technique et méthodologique.', 'Précisions sur le site web : - Site multi langues. - Responsive design : 2 points de rupture seront implémentés sur le site. - Compatible avec IE 9, 10, 11 ; FF, Chrome et Android 4. - Formulaire de contact multi-destinataire. - Inscription à des évènements avec compteur et email de remerciement (création/affichage d\'évènement, formulaire d\'inscription). - Module de cartographie avec affichage de puces sur les différents pays ou régions dans lesquels l\'association intervient. - Mise en place de pages interfacées avec des Webservices de la solution « profilsoft » pour la création d\'un section « offre d\'emploi ».', NULL, 'Admin', '2018-02-24 09:14:21'),
(61, 'Autre client', 'Médecins du Monde (ONG) - Association indépendante, Médecins du Monde agit au-delà du soin. Elle dénonce les atteintes à la dignité et aux droits de l\'homme et se bat pour améliorer la situation des populations. Dans le cadre de sa transformation digitale globale, l\'ONG Médecins du Monde désire réaliser la refonte de son site internet. Le projet global était piloté par DDB.', 'PUBLISHED', 'Le projet a consisté à : - Réaliser les spécifications techniques de la plate-forme ; - Assurer les développements techniques HTML du site ; - Assurer l\'intégration du site.', 'L\'objectif est de véhiculer une image « actuelle » : système de navigation moderne accessible depuis un ensemble de terminaux très divers. Il s\'agit de réaliser un accompagnement à la fois technique et méthodologique.', 'Précisions sur le site web : - Site multi langues. - Responsive design : 2 points de rupture seront implémentés sur le site. - Compatible avec IE 9, 10, 11 ; FF, Chrome et Android 4. - Formulaire de contact multi-destinataire. - Inscription à des évènements avec compteur et email de remerciement (création/affichage d\'évènement, formulaire d\'inscription). - Module de cartographie avec affichage de puces sur les différents pays ou régions dans lesquels l\'association intervient. - Mise en place de pages interfacées avec des Webservices de la solution « profilsoft » pour la création d\'un section « offre d\'emploi ».', NULL, 'Moha', '2018-02-24 09:14:21'),
(62, 'Medecins du monde', 'Médecins du Monde (ONG) - Association indépendante, Médecins du Monde agit au-delà du soin. Elle dénonce les atteintes à la dignité et aux droits de l\'homme et se bat pour améliorer la situation des populations. Dans le cadre de sa transformation digitale globale, l\'ONG Médecins du Monde désire réaliser la refonte de son site internet. Le projet global était piloté par DDB.', 'PUBLISHED', 'Le projet a consisté à : - Réaliser les spécifications techniques de la plate-forme ; - Assurer les développements techniques HTML du site ; - Assurer l\'intégration du site.', 'L\'objectif est de véhiculer une image « actuelle » : système de navigation moderne accessible depuis un ensemble de terminaux très divers. Il s\'agit de réaliser un accompagnement à la fois technique et méthodologique.', 'Précisions sur le site web : - Site multi langues. - Responsive design : 2 points de rupture seront implémentés sur le site. - Compatible avec IE 9, 10, 11 ; FF, Chrome et Android 4. - Formulaire de contact multi-destinataire. - Inscription à des évènements avec compteur et email de remerciement (création/affichage d\'évènement, formulaire d\'inscription). - Module de cartographie avec affichage de puces sur les différents pays ou régions dans lesquels l\'association intervient. - Mise en place de pages interfacées avec des Webservices de la solution « profilsoft » pour la création d\'un section « offre d\'emploi ».', NULL, 'Admin', '2018-02-24 09:14:21'),
(63, 'Autre client', 'Médecins du Monde (ONG) - Association indépendante, Médecins du Monde agit au-delà du soin. Elle dénonce les atteintes à la dignité et aux droits de l\'homme et se bat pour améliorer la situation des populations. Dans le cadre de sa transformation digitale globale, l\'ONG Médecins du Monde désire réaliser la refonte de son site internet. Le projet global était piloté par DDB.', 'PUBLISHED', 'Le projet a consisté à : - Réaliser les spécifications techniques de la plate-forme ; - Assurer les développements techniques HTML du site ; - Assurer l\'intégration du site.', 'L\'objectif est de véhiculer une image « actuelle » : système de navigation moderne accessible depuis un ensemble de terminaux très divers. Il s\'agit de réaliser un accompagnement à la fois technique et méthodologique.', 'Précisions sur le site web : - Site multi langues. - Responsive design : 2 points de rupture seront implémentés sur le site. - Compatible avec IE 9, 10, 11 ; FF, Chrome et Android 4. - Formulaire de contact multi-destinataire. - Inscription à des évènements avec compteur et email de remerciement (création/affichage d\'évènement, formulaire d\'inscription). - Module de cartographie avec affichage de puces sur les différents pays ou régions dans lesquels l\'association intervient. - Mise en place de pages interfacées avec des Webservices de la solution « profilsoft » pour la création d\'un section « offre d\'emploi ».', NULL, 'Admin', '2018-02-24 09:14:21'),
(64, 'Medecins du monde', 'Médecins du Monde (ONG) - Association indépendante, Médecins du Monde agit au-delà du soin. Elle dénonce les atteintes à la dignité et aux droits de l\'homme et se bat pour améliorer la situation des populations. Dans le cadre de sa transformation digitale globale, l\'ONG Médecins du Monde désire réaliser la refonte de son site internet. Le projet global était piloté par DDB.', 'PUBLISHED', 'Le projet a consisté à : - Réaliser les spécifications techniques de la plate-forme ; - Assurer les développements techniques HTML du site ; - Assurer l\'intégration du site.', 'L\'objectif est de véhiculer une image « actuelle » : système de navigation moderne accessible depuis un ensemble de terminaux très divers. Il s\'agit de réaliser un accompagnement à la fois technique et méthodologique.', 'Précisions sur le site web : - Site multi langues. - Responsive design : 2 points de rupture seront implémentés sur le site. - Compatible avec IE 9, 10, 11 ; FF, Chrome et Android 4. - Formulaire de contact multi-destinataire. - Inscription à des évènements avec compteur et email de remerciement (création/affichage d\'évènement, formulaire d\'inscription). - Module de cartographie avec affichage de puces sur les différents pays ou régions dans lesquels l\'association intervient. - Mise en place de pages interfacées avec des Webservices de la solution « profilsoft » pour la création d\'un section « offre d\'emploi ».', NULL, 'Moha', '2018-02-24 09:14:21'),
(65, 'Autre client', 'Médecins du Monde (ONG) - Association indépendante, Médecins du Monde agit au-delà du soin. Elle dénonce les atteintes à la dignité et aux droits de l\'homme et se bat pour améliorer la situation des populations. Dans le cadre de sa transformation digitale globale, l\'ONG Médecins du Monde désire réaliser la refonte de son site internet. Le projet global était piloté par DDB.', 'PUBLISHED', 'Le projet a consisté à : - Réaliser les spécifications techniques de la plate-forme ; - Assurer les développements techniques HTML du site ; - Assurer l\'intégration du site.', 'L\'objectif est de véhiculer une image « actuelle » : système de navigation moderne accessible depuis un ensemble de terminaux très divers. Il s\'agit de réaliser un accompagnement à la fois technique et méthodologique.', 'Précisions sur le site web : - Site multi langues. - Responsive design : 2 points de rupture seront implémentés sur le site. - Compatible avec IE 9, 10, 11 ; FF, Chrome et Android 4. - Formulaire de contact multi-destinataire. - Inscription à des évènements avec compteur et email de remerciement (création/affichage d\'évènement, formulaire d\'inscription). - Module de cartographie avec affichage de puces sur les différents pays ou régions dans lesquels l\'association intervient. - Mise en place de pages interfacées avec des Webservices de la solution « profilsoft » pour la création d\'un section « offre d\'emploi ».', NULL, 'Moha', '2018-02-24 09:14:21'),
(66, 'Medecins du monde', 'Médecins du Monde (ONG) - Association indépendante, Médecins du Monde agit au-delà du soin. Elle dénonce les atteintes à la dignité et aux droits de l\'homme et se bat pour améliorer la situation des populations. Dans le cadre de sa transformation digitale globale, l\'ONG Médecins du Monde désire réaliser la refonte de son site internet. Le projet global était piloté par DDB.', 'PUBLISHED', 'Le projet a consisté à : - Réaliser les spécifications techniques de la plate-forme ; - Assurer les développements techniques HTML du site ; - Assurer l\'intégration du site.', 'L\'objectif est de véhiculer une image « actuelle » : système de navigation moderne accessible depuis un ensemble de terminaux très divers. Il s\'agit de réaliser un accompagnement à la fois technique et méthodologique.', 'Précisions sur le site web : - Site multi langues. - Responsive design : 2 points de rupture seront implémentés sur le site. - Compatible avec IE 9, 10, 11 ; FF, Chrome et Android 4. - Formulaire de contact multi-destinataire. - Inscription à des évènements avec compteur et email de remerciement (création/affichage d\'évènement, formulaire d\'inscription). - Module de cartographie avec affichage de puces sur les différents pays ou régions dans lesquels l\'association intervient. - Mise en place de pages interfacées avec des Webservices de la solution « profilsoft » pour la création d\'un section « offre d\'emploi ».', NULL, 'Admin', '2018-02-24 09:14:21');
INSERT INTO `refs` (`id`, `client`, `context`, `status`, `objectifs`, `presentation`, `output`, `preview`, `createdBY`, `createdAT`) VALUES
(67, 'Autre client', 'Médecins du Monde (ONG) - Association indépendante, Médecins du Monde agit au-delà du soin. Elle dénonce les atteintes à la dignité et aux droits de l\'homme et se bat pour améliorer la situation des populations. Dans le cadre de sa transformation digitale globale, l\'ONG Médecins du Monde désire réaliser la refonte de son site internet. Le projet global était piloté par DDB.', 'PUBLISHED', 'Le projet a consisté à : - Réaliser les spécifications techniques de la plate-forme ; - Assurer les développements techniques HTML du site ; - Assurer l\'intégration du site.', 'L\'objectif est de véhiculer une image « actuelle » : système de navigation moderne accessible depuis un ensemble de terminaux très divers. Il s\'agit de réaliser un accompagnement à la fois technique et méthodologique.', 'Précisions sur le site web : - Site multi langues. - Responsive design : 2 points de rupture seront implémentés sur le site. - Compatible avec IE 9, 10, 11 ; FF, Chrome et Android 4. - Formulaire de contact multi-destinataire. - Inscription à des évènements avec compteur et email de remerciement (création/affichage d\'évènement, formulaire d\'inscription). - Module de cartographie avec affichage de puces sur les différents pays ou régions dans lesquels l\'association intervient. - Mise en place de pages interfacées avec des Webservices de la solution « profilsoft » pour la création d\'un section « offre d\'emploi ».', NULL, 'Admin', '2018-02-24 09:14:21'),
(68, 'Autre client', 'Médecins du Monde (ONG) - Association indépendante, Médecins du Monde agit au-delà du soin. Elle dénonce les atteintes à la dignité et aux droits de l\'homme et se bat pour améliorer la situation des populations. Dans le cadre de sa transformation digitale globale, l\'ONG Médecins du Monde désire réaliser la refonte de son site internet. Le projet global était piloté par DDB.', 'PUBLISHED', 'Le projet a consisté à : - Réaliser les spécifications techniques de la plate-forme ; - Assurer les développements techniques HTML du site ; - Assurer l\'intégration du site.', 'L\'objectif est de véhiculer une image « actuelle » : système de navigation moderne accessible depuis un ensemble de terminaux très divers. Il s\'agit de réaliser un accompagnement à la fois technique et méthodologique.', 'Précisions sur le site web : - Site multi langues. - Responsive design : 2 points de rupture seront implémentés sur le site. - Compatible avec IE 9, 10, 11 ; FF, Chrome et Android 4. - Formulaire de contact multi-destinataire. - Inscription à des évènements avec compteur et email de remerciement (création/affichage d\'évènement, formulaire d\'inscription). - Module de cartographie avec affichage de puces sur les différents pays ou régions dans lesquels l\'association intervient. - Mise en place de pages interfacées avec des Webservices de la solution « profilsoft » pour la création d\'un section « offre d\'emploi ».', NULL, 'Moha', '2018-02-24 09:14:21'),
(69, 'Medecins du monde', 'Médecins du Monde (ONG) - Association indépendante, Médecins du Monde agit au-delà du soin. Elle dénonce les atteintes à la dignité et aux droits de l\'homme et se bat pour améliorer la situation des populations. Dans le cadre de sa transformation digitale globale, l\'ONG Médecins du Monde désire réaliser la refonte de son site internet. Le projet global était piloté par DDB.', 'PUBLISHED', 'Le projet a consisté à : - Réaliser les spécifications techniques de la plate-forme ; - Assurer les développements techniques HTML du site ; - Assurer l\'intégration du site.', 'L\'objectif est de véhiculer une image « actuelle » : système de navigation moderne accessible depuis un ensemble de terminaux très divers. Il s\'agit de réaliser un accompagnement à la fois technique et méthodologique.', 'Précisions sur le site web : - Site multi langues. - Responsive design : 2 points de rupture seront implémentés sur le site. - Compatible avec IE 9, 10, 11 ; FF, Chrome et Android 4. - Formulaire de contact multi-destinataire. - Inscription à des évènements avec compteur et email de remerciement (création/affichage d\'évènement, formulaire d\'inscription). - Module de cartographie avec affichage de puces sur les différents pays ou régions dans lesquels l\'association intervient. - Mise en place de pages interfacées avec des Webservices de la solution « profilsoft » pour la création d\'un section « offre d\'emploi ».', NULL, 'Admin', '2018-02-24 09:14:21'),
(70, 'Autre client', 'Médecins du Monde (ONG) - Association indépendante, Médecins du Monde agit au-delà du soin. Elle dénonce les atteintes à la dignité et aux droits de l\'homme et se bat pour améliorer la situation des populations. Dans le cadre de sa transformation digitale globale, l\'ONG Médecins du Monde désire réaliser la refonte de son site internet. Le projet global était piloté par DDB.', 'PUBLISHED', 'Le projet a consisté à : - Réaliser les spécifications techniques de la plate-forme ; - Assurer les développements techniques HTML du site ; - Assurer l\'intégration du site.', 'L\'objectif est de véhiculer une image « actuelle » : système de navigation moderne accessible depuis un ensemble de terminaux très divers. Il s\'agit de réaliser un accompagnement à la fois technique et méthodologique.', 'Précisions sur le site web : - Site multi langues. - Responsive design : 2 points de rupture seront implémentés sur le site. - Compatible avec IE 9, 10, 11 ; FF, Chrome et Android 4. - Formulaire de contact multi-destinataire. - Inscription à des évènements avec compteur et email de remerciement (création/affichage d\'évènement, formulaire d\'inscription). - Module de cartographie avec affichage de puces sur les différents pays ou régions dans lesquels l\'association intervient. - Mise en place de pages interfacées avec des Webservices de la solution « profilsoft » pour la création d\'un section « offre d\'emploi ».', NULL, 'Admin', '2018-02-24 09:14:21'),
(71, 'Medecins du monde', 'Médecins du Monde (ONG) - Association indépendante, Médecins du Monde agit au-delà du soin. Elle dénonce les atteintes à la dignité et aux droits de l\'homme et se bat pour améliorer la situation des populations. Dans le cadre de sa transformation digitale globale, l\'ONG Médecins du Monde désire réaliser la refonte de son site internet. Le projet global était piloté par DDB.', 'PUBLISHED', 'Le projet a consisté à : - Réaliser les spécifications techniques de la plate-forme ; - Assurer les développements techniques HTML du site ; - Assurer l\'intégration du site.', 'L\'objectif est de véhiculer une image « actuelle » : système de navigation moderne accessible depuis un ensemble de terminaux très divers. Il s\'agit de réaliser un accompagnement à la fois technique et méthodologique.', 'Précisions sur le site web : - Site multi langues. - Responsive design : 2 points de rupture seront implémentés sur le site. - Compatible avec IE 9, 10, 11 ; FF, Chrome et Android 4. - Formulaire de contact multi-destinataire. - Inscription à des évènements avec compteur et email de remerciement (création/affichage d\'évènement, formulaire d\'inscription). - Module de cartographie avec affichage de puces sur les différents pays ou régions dans lesquels l\'association intervient. - Mise en place de pages interfacées avec des Webservices de la solution « profilsoft » pour la création d\'un section « offre d\'emploi ».', NULL, 'Moha', '2018-02-24 09:14:21'),
(72, 'Autre client', 'Médecins du Monde (ONG) - Association indépendante, Médecins du Monde agit au-delà du soin. Elle dénonce les atteintes à la dignité et aux droits de l\'homme et se bat pour améliorer la situation des populations. Dans le cadre de sa transformation digitale globale, l\'ONG Médecins du Monde désire réaliser la refonte de son site internet. Le projet global était piloté par DDB.', 'PUBLISHED', 'Le projet a consisté à : - Réaliser les spécifications techniques de la plate-forme ; - Assurer les développements techniques HTML du site ; - Assurer l\'intégration du site.', 'L\'objectif est de véhiculer une image « actuelle » : système de navigation moderne accessible depuis un ensemble de terminaux très divers. Il s\'agit de réaliser un accompagnement à la fois technique et méthodologique.', 'Précisions sur le site web : - Site multi langues. - Responsive design : 2 points de rupture seront implémentés sur le site. - Compatible avec IE 9, 10, 11 ; FF, Chrome et Android 4. - Formulaire de contact multi-destinataire. - Inscription à des évènements avec compteur et email de remerciement (création/affichage d\'évènement, formulaire d\'inscription). - Module de cartographie avec affichage de puces sur les différents pays ou régions dans lesquels l\'association intervient. - Mise en place de pages interfacées avec des Webservices de la solution « profilsoft » pour la création d\'un section « offre d\'emploi ».', NULL, 'Moha', '2018-02-24 09:14:21'),
(73, 'Medecins du monde', 'Médecins du Monde (ONG) - Association indépendante, Médecins du Monde agit au-delà du soin. Elle dénonce les atteintes à la dignité et aux droits de l\'homme et se bat pour améliorer la situation des populations. Dans le cadre de sa transformation digitale globale, l\'ONG Médecins du Monde désire réaliser la refonte de son site internet. Le projet global était piloté par DDB.', 'PUBLISHED', 'Le projet a consisté à : - Réaliser les spécifications techniques de la plate-forme ; - Assurer les développements techniques HTML du site ; - Assurer l\'intégration du site.', 'L\'objectif est de véhiculer une image « actuelle » : système de navigation moderne accessible depuis un ensemble de terminaux très divers. Il s\'agit de réaliser un accompagnement à la fois technique et méthodologique.', 'Précisions sur le site web : - Site multi langues. - Responsive design : 2 points de rupture seront implémentés sur le site. - Compatible avec IE 9, 10, 11 ; FF, Chrome et Android 4. - Formulaire de contact multi-destinataire. - Inscription à des évènements avec compteur et email de remerciement (création/affichage d\'évènement, formulaire d\'inscription). - Module de cartographie avec affichage de puces sur les différents pays ou régions dans lesquels l\'association intervient. - Mise en place de pages interfacées avec des Webservices de la solution « profilsoft » pour la création d\'un section « offre d\'emploi ».', NULL, 'Admin', '2018-02-24 09:14:21'),
(74, 'Autre client', 'Médecins du Monde (ONG) - Association indépendante, Médecins du Monde agit au-delà du soin. Elle dénonce les atteintes à la dignité et aux droits de l\'homme et se bat pour améliorer la situation des populations. Dans le cadre de sa transformation digitale globale, l\'ONG Médecins du Monde désire réaliser la refonte de son site internet. Le projet global était piloté par DDB.', 'PUBLISHED', 'Le projet a consisté à : - Réaliser les spécifications techniques de la plate-forme ; - Assurer les développements techniques HTML du site ; - Assurer l\'intégration du site.', 'L\'objectif est de véhiculer une image « actuelle » : système de navigation moderne accessible depuis un ensemble de terminaux très divers. Il s\'agit de réaliser un accompagnement à la fois technique et méthodologique.', 'Précisions sur le site web : - Site multi langues. - Responsive design : 2 points de rupture seront implémentés sur le site. - Compatible avec IE 9, 10, 11 ; FF, Chrome et Android 4. - Formulaire de contact multi-destinataire. - Inscription à des évènements avec compteur et email de remerciement (création/affichage d\'évènement, formulaire d\'inscription). - Module de cartographie avec affichage de puces sur les différents pays ou régions dans lesquels l\'association intervient. - Mise en place de pages interfacées avec des Webservices de la solution « profilsoft » pour la création d\'un section « offre d\'emploi ».', NULL, 'Admin', '2018-02-24 09:14:21'),
(75, 'Medecins du monde', 'Médecins du Monde (ONG) - Association indépendante, Médecins du Monde agit au-delà du soin. Elle dénonce les atteintes à la dignité et aux droits de l\'homme et se bat pour améliorer la situation des populations. Dans le cadre de sa transformation digitale globale, l\'ONG Médecins du Monde désire réaliser la refonte de son site internet. Le projet global était piloté par DDB.', 'PUBLISHED', 'Le projet a consisté à : - Réaliser les spécifications techniques de la plate-forme ; - Assurer les développements techniques HTML du site ; - Assurer l\'intégration du site.', 'L\'objectif est de véhiculer une image « actuelle » : système de navigation moderne accessible depuis un ensemble de terminaux très divers. Il s\'agit de réaliser un accompagnement à la fois technique et méthodologique.', 'Précisions sur le site web : - Site multi langues. - Responsive design : 2 points de rupture seront implémentés sur le site. - Compatible avec IE 9, 10, 11 ; FF, Chrome et Android 4. - Formulaire de contact multi-destinataire. - Inscription à des évènements avec compteur et email de remerciement (création/affichage d\'évènement, formulaire d\'inscription). - Module de cartographie avec affichage de puces sur les différents pays ou régions dans lesquels l\'association intervient. - Mise en place de pages interfacées avec des Webservices de la solution « profilsoft » pour la création d\'un section « offre d\'emploi ».', NULL, 'Moha', '2018-02-24 09:14:21'),
(76, 'Autre client', 'Médecins du Monde (ONG) - Association indépendante, Médecins du Monde agit au-delà du soin. Elle dénonce les atteintes à la dignité et aux droits de l\'homme et se bat pour améliorer la situation des populations. Dans le cadre de sa transformation digitale globale, l\'ONG Médecins du Monde désire réaliser la refonte de son site internet. Le projet global était piloté par DDB.', 'PUBLISHED', 'Le projet a consisté à : - Réaliser les spécifications techniques de la plate-forme ; - Assurer les développements techniques HTML du site ; - Assurer l\'intégration du site.', 'L\'objectif est de véhiculer une image « actuelle » : système de navigation moderne accessible depuis un ensemble de terminaux très divers. Il s\'agit de réaliser un accompagnement à la fois technique et méthodologique.', 'Précisions sur le site web : - Site multi langues. - Responsive design : 2 points de rupture seront implémentés sur le site. - Compatible avec IE 9, 10, 11 ; FF, Chrome et Android 4. - Formulaire de contact multi-destinataire. - Inscription à des évènements avec compteur et email de remerciement (création/affichage d\'évènement, formulaire d\'inscription). - Module de cartographie avec affichage de puces sur les différents pays ou régions dans lesquels l\'association intervient. - Mise en place de pages interfacées avec des Webservices de la solution « profilsoft » pour la création d\'un section « offre d\'emploi ».', NULL, 'Moha', '2018-02-24 09:14:21'),
(77, 'Medecins du monde', 'Médecins du Monde (ONG) - Association indépendante, Médecins du Monde agit au-delà du soin. Elle dénonce les atteintes à la dignité et aux droits de l\'homme et se bat pour améliorer la situation des populations. Dans le cadre de sa transformation digitale globale, l\'ONG Médecins du Monde désire réaliser la refonte de son site internet. Le projet global était piloté par DDB.', 'PUBLISHED', 'Le projet a consisté à : - Réaliser les spécifications techniques de la plate-forme ; - Assurer les développements techniques HTML du site ; - Assurer l\'intégration du site.', 'L\'objectif est de véhiculer une image « actuelle » : système de navigation moderne accessible depuis un ensemble de terminaux très divers. Il s\'agit de réaliser un accompagnement à la fois technique et méthodologique.', 'Précisions sur le site web : - Site multi langues. - Responsive design : 2 points de rupture seront implémentés sur le site. - Compatible avec IE 9, 10, 11 ; FF, Chrome et Android 4. - Formulaire de contact multi-destinataire. - Inscription à des évènements avec compteur et email de remerciement (création/affichage d\'évènement, formulaire d\'inscription). - Module de cartographie avec affichage de puces sur les différents pays ou régions dans lesquels l\'association intervient. - Mise en place de pages interfacées avec des Webservices de la solution « profilsoft » pour la création d\'un section « offre d\'emploi ».', NULL, 'Admin', '2018-02-24 09:14:21'),
(78, 'Autre client', 'Médecins du Monde (ONG) - Association indépendante, Médecins du Monde agit au-delà du soin. Elle dénonce les atteintes à la dignité et aux droits de l\'homme et se bat pour améliorer la situation des populations. Dans le cadre de sa transformation digitale globale, l\'ONG Médecins du Monde désire réaliser la refonte de son site internet. Le projet global était piloté par DDB.', 'PUBLISHED', 'Le projet a consisté à : - Réaliser les spécifications techniques de la plate-forme ; - Assurer les développements techniques HTML du site ; - Assurer l\'intégration du site.', 'L\'objectif est de véhiculer une image « actuelle » : système de navigation moderne accessible depuis un ensemble de terminaux très divers. Il s\'agit de réaliser un accompagnement à la fois technique et méthodologique.', 'Précisions sur le site web : - Site multi langues. - Responsive design : 2 points de rupture seront implémentés sur le site. - Compatible avec IE 9, 10, 11 ; FF, Chrome et Android 4. - Formulaire de contact multi-destinataire. - Inscription à des évènements avec compteur et email de remerciement (création/affichage d\'évènement, formulaire d\'inscription). - Module de cartographie avec affichage de puces sur les différents pays ou régions dans lesquels l\'association intervient. - Mise en place de pages interfacées avec des Webservices de la solution « profilsoft » pour la création d\'un section « offre d\'emploi ».', NULL, 'Admin', '2018-02-24 09:14:21'),
(79, 'Medecins du monde', 'Médecins du Monde (ONG) - Association indépendante, Médecins du Monde agit au-delà du soin. Elle dénonce les atteintes à la dignité et aux droits de l\'homme et se bat pour améliorer la situation des populations. Dans le cadre de sa transformation digitale globale, l\'ONG Médecins du Monde désire réaliser la refonte de son site internet. Le projet global était piloté par DDB.', 'PUBLISHED', 'Le projet a consisté à : - Réaliser les spécifications techniques de la plate-forme ; - Assurer les développements techniques HTML du site ; - Assurer l\'intégration du site.', 'L\'objectif est de véhiculer une image « actuelle » : système de navigation moderne accessible depuis un ensemble de terminaux très divers. Il s\'agit de réaliser un accompagnement à la fois technique et méthodologique.', 'Précisions sur le site web : - Site multi langues. - Responsive design : 2 points de rupture seront implémentés sur le site. - Compatible avec IE 9, 10, 11 ; FF, Chrome et Android 4. - Formulaire de contact multi-destinataire. - Inscription à des évènements avec compteur et email de remerciement (création/affichage d\'évènement, formulaire d\'inscription). - Module de cartographie avec affichage de puces sur les différents pays ou régions dans lesquels l\'association intervient. - Mise en place de pages interfacées avec des Webservices de la solution « profilsoft » pour la création d\'un section « offre d\'emploi ».', NULL, 'Moha', '2018-02-24 09:14:21'),
(80, 'Autre client', 'Médecins du Monde (ONG) - Association indépendante, Médecins du Monde agit au-delà du soin. Elle dénonce les atteintes à la dignité et aux droits de l\'homme et se bat pour améliorer la situation des populations. Dans le cadre de sa transformation digitale globale, l\'ONG Médecins du Monde désire réaliser la refonte de son site internet. Le projet global était piloté par DDB.', 'PUBLISHED', 'Le projet a consisté à : - Réaliser les spécifications techniques de la plate-forme ; - Assurer les développements techniques HTML du site ; - Assurer l\'intégration du site.', 'L\'objectif est de véhiculer une image « actuelle » : système de navigation moderne accessible depuis un ensemble de terminaux très divers. Il s\'agit de réaliser un accompagnement à la fois technique et méthodologique.', 'Précisions sur le site web : - Site multi langues. - Responsive design : 2 points de rupture seront implémentés sur le site. - Compatible avec IE 9, 10, 11 ; FF, Chrome et Android 4. - Formulaire de contact multi-destinataire. - Inscription à des évènements avec compteur et email de remerciement (création/affichage d\'évènement, formulaire d\'inscription). - Module de cartographie avec affichage de puces sur les différents pays ou régions dans lesquels l\'association intervient. - Mise en place de pages interfacées avec des Webservices de la solution « profilsoft » pour la création d\'un section « offre d\'emploi ».', NULL, 'Moha', '2018-02-24 09:14:21'),
(81, 'Medecins du monde', 'Médecins du Monde (ONG) - Association indépendante, Médecins du Monde agit au-delà du soin. Elle dénonce les atteintes à la dignité et aux droits de l\'homme et se bat pour améliorer la situation des populations. Dans le cadre de sa transformation digitale globale, l\'ONG Médecins du Monde désire réaliser la refonte de son site internet. Le projet global était piloté par DDB.', 'PUBLISHED', 'Le projet a consisté à : - Réaliser les spécifications techniques de la plate-forme ; - Assurer les développements techniques HTML du site ; - Assurer l\'intégration du site.', 'L\'objectif est de véhiculer une image « actuelle » : système de navigation moderne accessible depuis un ensemble de terminaux très divers. Il s\'agit de réaliser un accompagnement à la fois technique et méthodologique.', 'Précisions sur le site web : - Site multi langues. - Responsive design : 2 points de rupture seront implémentés sur le site. - Compatible avec IE 9, 10, 11 ; FF, Chrome et Android 4. - Formulaire de contact multi-destinataire. - Inscription à des évènements avec compteur et email de remerciement (création/affichage d\'évènement, formulaire d\'inscription). - Module de cartographie avec affichage de puces sur les différents pays ou régions dans lesquels l\'association intervient. - Mise en place de pages interfacées avec des Webservices de la solution « profilsoft » pour la création d\'un section « offre d\'emploi ».', NULL, 'Admin', '2018-02-24 09:14:21'),
(83, 'Medecins du monde', 'Médecins du Monde (ONG) - Association indépendante, Médecins du Monde agit au-delà du soin. Elle dénonce les atteintes à la dignité et aux droits de l\'homme et se bat pour améliorer la situation des populations. Dans le cadre de sa transformation digitale globale, l\'ONG Médecins du Monde désire réaliser la refonte de son site internet. Le projet global était piloté par DDB.', 'PUBLISHED', 'Le projet a consisté à : - Réaliser les spécifications techniques de la plate-forme ; - Assurer les développements techniques HTML du site ; - Assurer l\'intégration du site.', 'L\'objectif est de véhiculer une image « actuelle » : système de navigation moderne accessible depuis un ensemble de terminaux très divers. Il s\'agit de réaliser un accompagnement à la fois technique et méthodologique.', 'Précisions sur le site web : - Site multi langues. - Responsive design : 2 points de rupture seront implémentés sur le site. - Compatible avec IE 9, 10, 11 ; FF, Chrome et Android 4. - Formulaire de contact multi-destinataire. - Inscription à des évènements avec compteur et email de remerciement (création/affichage d\'évènement, formulaire d\'inscription). - Module de cartographie avec affichage de puces sur les différents pays ou régions dans lesquels l\'association intervient. - Mise en place de pages interfacées avec des Webservices de la solution « profilsoft » pour la création d\'un section « offre d\'emploi ».', '../img/wordpress.png', 'Moha', '2018-02-24 09:14:21'),
(84, 'Autre client', 'Médecins du Monde (ONG) - Association indépendante, Médecins du Monde agit au-delà du soin. Elle dénonce les atteintes à la dignité et aux droits de l\'homme et se bat pour améliorer la situation des populations. Dans le cadre de sa transformation digitale globale, l\'ONG Médecins du Monde désire réaliser la refonte de son site internet. Le projet global était piloté par DDB.', 'PUBLISHED', 'Le projet a consisté à : - Réaliser les spécifications techniques de la plate-forme ; - Assurer les développements techniques HTML du site ; - Assurer l\'intégration du site.', 'L\'objectif est de véhiculer une image « actuelle » : système de navigation moderne accessible depuis un ensemble de terminaux très divers. Il s\'agit de réaliser un accompagnement à la fois technique et méthodologique.', 'Précisions sur le site web : - Site multi langues. - Responsive design : 2 points de rupture seront implémentés sur le site. - Compatible avec IE 9, 10, 11 ; FF, Chrome et Android 4. - Formulaire de contact multi-destinataire. - Inscription à des évènements avec compteur et email de remerciement (création/affichage d\'évènement, formulaire d\'inscription). - Module de cartographie avec affichage de puces sur les différents pays ou régions dans lesquels l\'association intervient. - Mise en place de pages interfacées avec des Webservices de la solution « profilsoft » pour la création d\'un section « offre d\'emploi ».', '../img/MAIF.jpg', 'Moha', '2018-02-24 09:14:21');

-- --------------------------------------------------------

--
-- Structure de la table `users`
--

CREATE TABLE `users` (
  `id` int(12) NOT NULL,
  `username` varchar(15) NOT NULL,
  `password` varchar(150) NOT NULL,
  `mail` varchar(100) NOT NULL,
  `lastview` int(10) NOT NULL,
  `lastconnection` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `createdAT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Contenu de la table `users`
--

INSERT INTO `users` (`id`, `username`, `password`, `mail`, `lastview`, `lastconnection`, `createdAT`) VALUES
(1, 'Admin', '69691e65ae0678b6a10ada73858b2554497e8dc1', 'Admin@admin.fr', 0, '2018-02-23 22:42:24', '2018-02-18 21:45:52'),
(2, 'Moha', '55cbe7fd00627a28668d1d7c9899bdb602dad69d', 'Admin@admin.fr', 83, '2018-02-26 21:22:22', '2018-02-22 23:00:00'),
(3, 'Cesar', '8eee89c994b90ad49540aa5dcd839138c25e0c96', 'Admin@admin.fr', 85, '2018-02-24 18:10:44', '2018-02-22 23:00:00'),
(4, 'Aicha', 'd714e6484bd3010a21fe887d0b37a07132c2c097', 'Admin@admin.fr', 0, '2018-02-24 16:30:41', '2018-02-22 23:00:00');

--
-- Index pour les tables exportées
--

--
-- Index pour la table `refs`
--
ALTER TABLE `refs`
  ADD PRIMARY KEY (`id`);

--
-- Index pour la table `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT pour les tables exportées
--

--
-- AUTO_INCREMENT pour la table `refs`
--
ALTER TABLE `refs`
  MODIFY `id` int(15) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=90;
--
-- AUTO_INCREMENT pour la table `users`
--
ALTER TABLE `users`
  MODIFY `id` int(12) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=5;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
